name: Firestore backup

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: lfdm/firestore-backup-gh-action@v1.0.0
        with:
          gcloudAuth: ${{ secrets.FIREBASE_BACKUP_GCLOUD_AUTH }}
          projectId: ${{ secrets.gcloud_project_id }}
          storageBucket: gs://astar-apps-bkp
